/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBMSProject;

import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.*;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Apurv Patel
 */
public class addEmployee extends javax.swing.JFrame {

    /**
     * Creates new form addEmployee
     */
    
    JTextFieldDateEditor dtEditor;
    
    public addEmployee() {
        initComponents();
        initDateEditor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblAmount6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDesignation = new javax.swing.JLabel();
        txtDesignation = new javax.swing.JTextField();
        lblphno = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        lblDob1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblGender = new javax.swing.JLabel();
        rdoFemale = new javax.swing.JRadioButton();
        rdoMale = new javax.swing.JRadioButton();
        txtDob = new javax.swing.JTextField();
        lblEmailID = new javax.swing.JLabel();
        txtEmailID = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblAmount1 = new javax.swing.JLabel();
        lblAmount2 = new javax.swing.JLabel();
        lblAmount3 = new javax.swing.JLabel();
        lblAmount4 = new javax.swing.JLabel();
        lblAmount5 = new javax.swing.JLabel();
        lblAmount7 = new javax.swing.JLabel();
        lblAmount8 = new javax.swing.JLabel();
        txtTA = new javax.swing.JTextField();
        txtMA = new javax.swing.JTextField();
        txtHRA = new javax.swing.JTextField();
        txtIncentive = new javax.swing.JTextField();
        txtBSA = new javax.swing.JTextField();
        txtLoan = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();

        lblAmount6.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblAmount6.setText("Basic Salary Amount:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Employee");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblName.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblName.setText("Name:");

        txtName.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        lblDesignation.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblDesignation.setText("Designation:");

        txtDesignation.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        lblphno.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblphno.setText("Employee ID:");

        txtEmpID.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        lblDob.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblDob.setText("DOB:");

        lblDob1.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblDob1.setText("Address:");

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        lblGender.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblGender.setText("Gender:");

        buttonGroup1.add(rdoFemale);
        rdoFemale.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        rdoFemale.setText("Female");

        buttonGroup1.add(rdoMale);
        rdoMale.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        rdoMale.setText("Male");
        rdoMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMaleActionPerformed(evt);
            }
        });

        txtDob.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        lblEmailID.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblEmailID.setText("Email ID:");

        txtEmailID.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        lblPhone.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblPhone.setText("Phone No.");

        txtPhone.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblDesignation)
                    .addComponent(lblphno)
                    .addComponent(lblDob)
                    .addComponent(lblDob1)
                    .addComponent(lblGender)
                    .addComponent(lblEmailID)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(rdoFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphno)
                    .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesignation)
                    .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDob)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoMale)
                        .addComponent(rdoFemale)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailID)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDob1))
                .addGap(45, 45, 45))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 470));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAmount1.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblAmount1.setText("Travel Allowance:");

        lblAmount2.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblAmount2.setText("Medical Allowance:");

        lblAmount3.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblAmount3.setText("House Rent Allowance:");

        lblAmount4.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblAmount4.setText("Incentive:");

        lblAmount5.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblAmount5.setText("Basic Salary Amount:");

        lblAmount7.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblAmount7.setText("Loan:");

        lblAmount8.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        lblAmount8.setText("Tax:");

        txtTA.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        txtMA.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        txtHRA.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        txtIncentive.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        txtBSA.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        txtLoan.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        txtTax.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmount3)
                            .addComponent(lblAmount2)
                            .addComponent(lblAmount1)
                            .addComponent(lblAmount4)
                            .addComponent(lblAmount5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBSA, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIncentive, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTA, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMA, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHRA, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmount7)
                            .addComponent(lblAmount8))
                        .addGap(131, 131, 131)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount1)
                    .addComponent(txtTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount2)
                    .addComponent(txtMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount3)
                    .addComponent(txtHRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount4)
                    .addComponent(txtIncentive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount5)
                    .addComponent(txtBSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount7)
                    .addComponent(txtLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount8)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 480, 460));

        btnInsert.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdoMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMaleActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/payrollManagementSystem","root","pi~3.14OR22/7");
            
            String query = "insert into employee values(?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(query);
            
            String query1 = "insert into Emp_Email values(?, ?)";
            PreparedStatement pstmt1 = conn.prepareStatement(query1);
            
            String query2 = "insert into Emp_PhoneN values(?, ?)";
            PreparedStatement pstmt2 = conn.prepareStatement(query2);
            
            String query3 = "insert into Salary values(?, ?, ?, ?)";
            PreparedStatement pstmt3 = conn.prepareStatement(query3);
            
            String query4 = "insert into deduction values(?, ?, ?)";
            PreparedStatement pstmt4 = conn.prepareStatement(query4);
            
            pstmt.setInt(1, Integer.parseInt(txtEmpID.getText()));
            pstmt.setString(2, txtName.getText());
            pstmt.setString(3, txtAddress.getText());
            pstmt.setString(4, txtDesignation.getText());
            pstmt.setInt(6, Integer.parseInt(txtDob.getText()));
            // pstmt.setInt(6, Integer.parseInt(txtAge.getText()));
            String gender = null;
            if(rdoMale.isSelected())
                gender = rdoMale.getText();
            if(rdoFemale.isSelected())
                gender = rdoFemale.getText();
            
            pstmt.setString(5, gender);
            
            pstmt1.setInt(1, Integer.parseInt(txtEmpID.getText()));
            pstmt1.setString(2, txtEmailID.getText());
            
            pstmt2.setInt(1, Integer.parseInt(txtEmpID.getText()));
            pstmt2.setString(2, txtPhone.getText());
            
            pstmt3.setInt(4, Integer.parseInt(txtEmpID.getText()));
            pstmt3.setInt(1, Integer.parseInt(txtBSA.getText()));
            
            float TA, MA, HRA, Total_Allowance;
            TA = Float.parseFloat(txtTA.getText());
            MA = Float.parseFloat(txtMA.getText());
            HRA = Float.parseFloat(txtHRA.getText());
            Total_Allowance = TA + MA + HRA;
            // JOptionPane.showMessageDialog(Calculator.this, "Result: " + String.valueOf(result));
            pstmt3.setFloat(2, Total_Allowance);
            
            // pstmt3.setInt(6, Integer.parseInt(txtWSD.getText()));
            pstmt3.setInt(3, Integer.parseInt(txtIncentive.getText()));
            
            pstmt4.setInt(3, Integer.parseInt(txtEmpID.getText()));
            pstmt4.setInt(1, Integer.parseInt(txtTax.getText()));
            pstmt4.setInt(2, Integer.parseInt(txtLoan.getText()));
            
            pstmt.executeUpdate();
            pstmt1.executeUpdate();
            pstmt2.executeUpdate();
            pstmt3.executeUpdate();
            pstmt4.executeUpdate();
            JOptionPane.showMessageDialog(null, "Insertion Successful");
            conn.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployee().setVisible(true);
            }
        });
    }
    
    private void initDateEditor() {
        // dtEditor = (JTextFieldDateEditor) dtDob.getDateEditor();
        // dtEditor.setEditable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmount1;
    private javax.swing.JLabel lblAmount2;
    private javax.swing.JLabel lblAmount3;
    private javax.swing.JLabel lblAmount4;
    private javax.swing.JLabel lblAmount5;
    private javax.swing.JLabel lblAmount6;
    private javax.swing.JLabel lblAmount7;
    private javax.swing.JLabel lblAmount8;
    private javax.swing.JLabel lblDesignation;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblDob1;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblphno;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtBSA;
    private javax.swing.JTextField txtDesignation;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtHRA;
    private javax.swing.JTextField txtIncentive;
    private javax.swing.JTextField txtLoan;
    private javax.swing.JTextField txtMA;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTA;
    private javax.swing.JTextField txtTax;
    // End of variables declaration//GEN-END:variables
}
