/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBMSProject;

/**
 *
 * @author Apurv Patel
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogoutAdmin2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAddEmp = new javax.swing.JButton();
        btnComDetails = new javax.swing.JButton();
        btnGenSal = new javax.swing.JButton();
        btnEmpRecords = new javax.swing.JButton();
        btnLogoutAdmin = new javax.swing.JButton();

        btnLogoutAdmin2.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        btnLogoutAdmin2.setText("Manage Leave");
        btnLogoutAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutAdmin2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAddEmp.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        btnAddEmp.setText("Add Employee");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });

        btnComDetails.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        btnComDetails.setText("Company Details");
        btnComDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComDetailsActionPerformed(evt);
            }
        });

        btnGenSal.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        btnGenSal.setText("Salary Report");
        btnGenSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenSalActionPerformed(evt);
            }
        });

        btnEmpRecords.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        btnEmpRecords.setText("Employee Records");
        btnEmpRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpRecordsActionPerformed(evt);
            }
        });

        btnLogoutAdmin.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        btnLogoutAdmin.setText("Logout");
        btnLogoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEmpRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogoutAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenSal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(btnAddEmp)
                .addGap(23, 23, 23)
                .addComponent(btnComDetails)
                .addGap(18, 18, 18)
                .addComponent(btnGenSal)
                .addGap(25, 25, 25)
                .addComponent(btnEmpRecords)
                .addGap(18, 18, 18)
                .addComponent(btnLogoutAdmin)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnLogoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutAdminActionPerformed
        // TODO add your handling code here:
        new AdminLogin().show();
        dispose();
    }//GEN-LAST:event_btnLogoutAdminActionPerformed

    private void btnComDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComDetailsActionPerformed
        // TODO add your handling code here:
        new CompanyDetails().show();
    }//GEN-LAST:event_btnComDetailsActionPerformed

    private void btnLogoutAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutAdmin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutAdmin2ActionPerformed

    private void btnGenSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenSalActionPerformed
        // TODO add your handling code here:
        new generate_salary().show();
    }//GEN-LAST:event_btnGenSalActionPerformed

    private void btnEmpRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpRecordsActionPerformed
        // TODO add your handling code here:
        new empRecords().show();
    }//GEN-LAST:event_btnEmpRecordsActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        // TODO add your handling code here:
        new addEmployee().show();
    }//GEN-LAST:event_btnAddEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnComDetails;
    private javax.swing.JButton btnEmpRecords;
    private javax.swing.JButton btnGenSal;
    private javax.swing.JButton btnLogoutAdmin;
    private javax.swing.JButton btnLogoutAdmin2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
