/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBMSProject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Apurv Patel
 */
public class generate_salary extends javax.swing.JFrame {

    /**
     * Creates new form generate_salary
     */
    public generate_salary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSalAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotalAllowance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIncentive = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLoan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 116, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jLabel1.setText("Basic Amount:");

        txtSalAmount.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jLabel4.setText("Total Allowance:");

        txtTotalAllowance.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jLabel5.setText("Incentive:");

        txtIncentive.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jLabel6.setText("Tax:");

        txtTax.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jLabel7.setText("Loan:");

        txtLoan.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIncentive, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIncentive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 410, 420));

        jLabel2.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jLabel2.setText("Employee ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 77, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jLabel3.setText("Employee ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 77, -1, -1));

        txtEmpID.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        getContentPane().add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 74, 181, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/payrollManagementSystem","root","pi~3.14OR22/7");
            
            String query = "select * from salary where Employee_ID = ?";
            PreparedStatement pstmt = conn.prepareStatement(query);
            
            String query1 = "select * from deduction where Employee_ID = ?";
            PreparedStatement pstmt1 = conn.prepareStatement(query1);
            
//            String query2 = "select * from Emp_PhoneN where Employee_ID = ?";
//            PreparedStatement pstmt2 = conn.prepareStatement(query2);
            
            pstmt.setInt(1 , Integer.parseInt(txtEmpID.getText()));
            pstmt1.setInt(1, Integer.parseInt(txtEmpID.getText()));
//            pstmt2.setInt(1, Integer.parseInt(txtEmpID.getText()));
            
            ResultSet rs = pstmt.executeQuery();
            if(rs.next())
            {
                // txtEmpID1.setText(rs.getString("Employee_ID"));
                //txtName.setText(rs.getString("Name"));
                txtSalAmount.setText(rs.getString("Basic_Salary_Amount"));
                txtTotalAllowance.setText(rs.getString("Total_Allowance"));
                txtIncentive.setText(rs.getString("Incentive"));
//                txtTax.setText(rs.getString("Tax"));
//                txtLoan.setText(rs.getString("Loan"));
                
                // txtAge.setText(rs.getString("Age"));
            }
//            else {
//                JOptionPane.showMessageDialog(null, "Not Found!");
//            }
            
            ResultSet rs1 = pstmt1.executeQuery();
            if(rs1.next())
            {
                txtTax.setText(rs1.getString("Tax"));
                txtLoan.setText(rs1.getString("Loan"));
            }
//            
//            ResultSet rs2 = pstmt2.executeQuery();
//            if(rs2.next())
//            {
//                txtPhone.setText(rs2.getString("Phone_number"));
//            }
            conn.close();
            
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generate_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generate_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generate_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generate_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generate_salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtIncentive;
    private javax.swing.JTextField txtLoan;
    private javax.swing.JTextField txtSalAmount;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotalAllowance;
    // End of variables declaration//GEN-END:variables
}
