/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBMSProject;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Apurv Patel
 */
public class loginEmployee extends javax.swing.JFrame {

    /**
     * Creates new form loginEmployee
     */
    public loginEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEmpLogin = new javax.swing.JButton();
        txtEmpPw = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtEmpUn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Login");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Nova", 0, 14))); // NOI18N

        btnEmpLogin.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        btnEmpLogin.setText("Login");
        btnEmpLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpLoginActionPerformed(evt);
            }
        });

        txtEmpPw.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        txtEmpPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmpPwKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Nova", 0, 12)); // NOI18N
        jLabel3.setText("Password");

        txtEmpUn.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        txtEmpUn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmpUnMouseClicked(evt);
            }
        });
        txtEmpUn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpUnActionPerformed(evt);
            }
        });
        txtEmpUn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmpUnKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Nova", 0, 12)); // NOI18N
        jLabel2.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtEmpUn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmpPw, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmpUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmpPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmpLogin)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpLoginActionPerformed
        // TODO add your handling code here:
        if(txtEmpUn.getText().isEmpty() || txtEmpPw.getText().isEmpty())
            JOptionPane.showMessageDialog(loginEmployee.this, "Enter Username and Password.");
        else if(txtEmpUn.getText().equals("1") && txtEmpPw.getText().equals("1")) {
            new employeeLogin().show();
        } else {
            JOptionPane.showMessageDialog(loginEmployee.this, "Enter correct Username and Password.");
        }
        txtEmpPw.setText("");
        dispose();
    }//GEN-LAST:event_btnEmpLoginActionPerformed

    private void txtEmpPwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpPwKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(txtEmpUn.getText().isEmpty() || txtEmpPw.getText().isEmpty())
            JOptionPane.showMessageDialog(loginEmployee.this, "Enter Username and Password.");
            else if(txtEmpUn.getText().equals("e1") && txtEmpPw.getText().equals("e1")) {
                new employeeLogin().show();
            } else {
                JOptionPane.showMessageDialog(loginEmployee.this, "Enter correct Username and Password.");
            }
            txtEmpPw.setText("");
            dispose();
        }
    }//GEN-LAST:event_txtEmpPwKeyPressed

    private void txtEmpUnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmpUnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpUnMouseClicked

    private void txtEmpUnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpUnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpUnActionPerformed

    private void txtEmpUnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpUnKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtEmpPw.grabFocus();
        }
    }//GEN-LAST:event_txtEmpUnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtEmpPw;
    private javax.swing.JTextField txtEmpUn;
    // End of variables declaration//GEN-END:variables
}
